// Central config for GHL SaaS checkout ("sale") links.
// These are the card-upfront, 14-day-trial payment links generated by the
// SaaS Configurator (app.dusa.studio → SaaS Configurator → plan → Sale link).
// One place to update; /start renders everything from here.
// TODO: replace the '#pending' values with the real AUD sale links.

export type BillingCycle = 'monthly' | 'annual';

export interface SaasPlan {
  id: string;
  name: string;
  blurb: string;
  monthlyPrice: number; // AUD
  annualPrice: number; // AUD, 2 months free
  highlight: boolean;
  features: string[];
  links: Record<BillingCycle, string>;
}

export const SAAS_PLANS: SaasPlan[] = [
  {
    id: 'launchpad',
    name: 'Launchpad',
    blurb: 'Pick any single core system and get started today.',
    monthlyPrice: 47,
    annualPrice: 470,
    highlight: false,
    features: [
      '1 core system of your choice',
      'Full dashboard access',
      'AI chat support',
      'Basic analytics',
    ],
    links: {
      monthly: '#pending',
      annual: '#pending',
    },
  },
  {
    id: 'starter',
    name: 'Starter',
    blurb: 'Everything connected. All 9 core systems under one login.',
    monthlyPrice: 149,
    annualPrice: 1490,
    highlight: true,
    features: [
      'All 9 core systems',
      'CRM, email, SMS, funnels & booking',
      'AI automations included',
      'Email support',
    ],
    links: {
      monthly: '#pending',
      annual: '#pending',
    },
  },
  {
    id: 'growth',
    name: 'Growth',
    blurb: 'Built for momentum. Unlimited contacts and priority support.',
    monthlyPrice: 297,
    annualPrice: 2970,
    highlight: false,
    features: [
      'Everything in Starter',
      'Unlimited contacts & users',
      'Advanced automations',
      'Priority support + account manager',
    ],
    links: {
      monthly: '#pending',
      annual: '#pending',
    },
  },
];
